import React from 'react';
import { ShieldAlert } from 'lucide-react';

export const TermsEN = () => (
    <div className="space-y-12 text-sm leading-relaxed text-slate-400 font-medium">
        <div className="p-6 bg-red-900/10 border border-red-500/20 rounded-2xl">
            <div className="flex items-start gap-4">
                <div className="p-3 bg-red-500/10 rounded-xl shrink-0">
                    <ShieldAlert size={24} className="text-red-500" />
                </div>
                <div className="space-y-3 text-red-100/90">
                    <h3 className="text-base font-bold text-red-400 tracking-widest">CRITICAL LEGAL DISCLAIMER - NO FINANCIAL ADVICE</h3>
                    <p>
                        All information on Synapse Capital (hereinafter "this site") is for educational, research, and informational purposes only and <strong>does not constitute investment advice</strong> under any circumstances.
                    </p>
                    <p>
                        Predictions, analysis, and scores generated by AI are simulations based on historical data and specific algorithms, and do not guarantee future market trends or profits. We assume no responsibility for any losses incurred from financial transactions made using the information on this site. All investment decisions must be made at the user's sole risk and responsibility.
                    </p>
                </div>
            </div>
        </div>

        <section className="space-y-4">
            <h2 className="text-lg font-bold text-white tracking-widest flex items-center gap-2">
                <span className="text-indigo-500 font-mono">Article 1</span> Applicability
            </h2>
            <p>
                These terms apply to all relationships involving the use of the services between the user and this site. By using this site, the user is deemed to have agreed to all the conditions of these terms.
            </p>
        </section>

        <section className="space-y-4">
            <h2 className="text-lg font-bold text-white tracking-widest flex items-center gap-2">
                <span className="text-indigo-500 font-mono">Article 2</span> Provided Intelligence Services
            </h2>
            <p>
                This site publishes automated financial market analysis and reports (hereinafter "provided data") using multiple LLMs (Large Language Models) and market APIs. The provided data is for technical demonstration and experimental purposes and we do not guarantee its accuracy, completeness, or timeliness.
            </p>
        </section>

        <section className="space-y-4">
            <h2 className="text-lg font-bold text-white tracking-widest flex items-center gap-2">
                <span className="text-indigo-500 font-mono">Article 3</span> Prohibited Actions
            </h2>
            <p>The user must not perform the following actions when using this site:</p>
            <ul className="list-disc pl-6 space-y-2 mt-4 marker:text-indigo-500">
                <li>Excessive extraction or attacks on this site's content or APIs using scraping programs or automation tools.</li>
                <li>Attempting intentional market manipulation using this site's AI system.</li>
                <li>Unauthorized sale or provision to third parties of the analysis data provided by this site as an "investment advisory business."</li>
                <li>Any other actions deemed inappropriate by this site.</li>
            </ul>
        </section>

        <section className="space-y-4">
            <h2 className="text-lg font-bold text-white tracking-widest flex items-center gap-2">
                <span className="text-indigo-500 font-mono">Article 4</span> Suspension or Interruption of Service
            </h2>
            <p>
                This site may suspend or interrupt all or part of the provision of services without prior notice to the user if it determines that any of the following grounds exist:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-4 marker:text-indigo-500">
                <li>Performing maintenance or updates on the system or APIs.</li>
                <li>Cases where there is a risk that AI inference results will be significantly inaccurate due to abnormal market fluctuations.</li>
                <li>Failure of external API providers (Google, OpenRouter, financial data APIs).</li>
            </ul>
        </section>

        <section className="space-y-4">
            <h2 className="text-lg font-bold text-white tracking-widest flex items-center gap-2">
                <span className="text-indigo-500 font-mono">Article 5</span> Copyright and Intellectual Property Rights
            </h2>
            <p>
                Copyrights and other intellectual property rights for content within this site (reports, data structures, UI design, etc.) belong in principle to this site or legitimate rights holders. Users may not perform unauthorized reproduction or secondary distribution beyond the scope of personal use.
            </p>
        </section>

        <section className="space-y-4 pt-8 border-t border-slate-800/50">
            <h2 className="text-lg font-bold text-white tracking-widest flex items-center gap-2">
                <span className="text-indigo-500 font-mono">Article 6</span> Contact Information
            </h2>
            <p>
                For inquiries regarding these terms, please contact the following email address:
            </p>
            <p className="text-indigo-400 font-mono mt-2">
                <a href="mailto:info@agent-frontier.jp" className="hover:underline">info@agent-frontier.jp</a>
            </p>
        </section>
    </div>
);
